name: Comment Trigger

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: read
  contents: read

jobs:
  trigger_tests:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/run-tests')
    runs-on: ubuntu-latest
    uses: ./.github/workflows/test-execution.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
