# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: run tests

on:
  workflow_call:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_type != 'tag' }}

jobs:
  run_tests:
    runs-on: macos-15
    steps:
    - name: Set Xcode 16.2.0
      run: sudo xcode-select -s /Applications/Xcode_16.2.0.app/Contents/Developer
    - name: Print Current Xcode
      run: xcode-select -p
    - uses: actions/checkout@v3
    - name: Run Cocoapods
      run: pod install
    - name: Sourcery
      run: |
        brew install sourcery
        sourcery --config .sourcery.yml
    - name: Generate AdamantSecret (for migration)
      run: |
        echo 'import Foundation
        enum AdamantSecret {
            static let appIdentifierPrefix: String = "random.string"
            static let keychainValuePassword: String = "random.string.two"
            static let oldKeychainPass: String = "random.string.three"
        }' > CommonKit/Sources/CommonKit/AdamantSecret.swift
    - name: Run tests
      run: xcodebuild test -workspace Adamant.xcworkspace -scheme Adamant.Dev -destination 'platform=iOS Simulator,name=iPhone 16'

 
