name: Trello
on:
    pull_request:
        types: [opened, edited, closed, reopened, ready_for_review, converted_to_draft]
jobs:
    trello:
        runs-on: ubuntu-latest
        steps:
            - uses: rematocorp/trello-integration-action@v9
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  trello-api-key: ${{ secrets.TRELLO_API_KEY }}
                  trello-auth-token: ${{ secrets.TRELLO_AUTH_TOKEN }}
                  trello-list-id-pr-open: ${{ secrets.TRELLO_LIST_ID_IN_REVIEW }}
                  trello-list-id-pr-merged: ${{ secrets.TRELLO_LIST_ID_IN_DEVELOP }}
                  trello-list-id-pr-draft: ${{ secrets.TRELLO_LIST_ID_IN_PROGRESS }}